@startuml
class Jogador{
Int Turno
Navio navios
}

class Tabuleiro{
- Tile[][] tiles
Tile tile_selecionado
GreenfootImage quadro
}

class World #LightGreen{
}

Tabuleiro --|> World
Menu --|> World

interface Navio {
Bool selecionado

getVida()
getPos()
void atirar()
}

Enum Sprite {
MAR
MARGEM
TERRA
MONTANHA
}


class Tile {
Greenfootimage image
}

class NavioGrande {
}

class NavioMedio {
}

class NavioPequeno {
}

class Singleton {
+ {static} int tile_tamanho
+ {static} int largura
+ {static} int altura
}

' classe implementa ..|> interface'

NavioGrande ..|> Navio
NavioMedio ..|> Navio
NavioPequeno ..|> Navio
Sprite --* Tile
Tile --* Tabuleiro
Jogador --* Navio

@enduml
